import type { Scenario } from '@/types'

export const scenarios: Scenario[] = [
  {
    id: 'auto-resolve',
    name: 'Auto-Resolve',
    description: 'Routine authorization error - high confidence auto-resolution',
    icon: 'CheckCircle',
    color: 'green',
    incident: {
      id: 'INC001234',
      title: 'Cannot access SAP GUI',
      description: 'User getting authorization error DYNP 138 when trying to login to SAP GUI. The user was able to login yesterday but today receives an authorization popup with error code DYNP 138.',
      error_code: 'DYNP 138',
      component: 'SAP Authorization',
      severity: 'Medium',
      user_email: 'john.doe@company.com',
      user_impact: 'Single user unable to work',
    },
    expectedConfidence: 92,
    expectedPath: 'auto_resolve',
    resolution: [
      'Open transaction SU01',
      'Enter username in the User field',
      'Navigate to Roles tab',
      'Click User Compare button',
      'Execute profile regeneration',
      'Run transaction SU25 to verify',
      'Test user login',
    ],
    timeSaved: '2 hours',
    costSaved: '$60',
    slaMinutes: 30,
  },
  {
    id: 'assisted',
    name: 'Assisted Resolution',
    description: 'Performance issue requiring analyst investigation',
    icon: 'UserCog',
    color: 'yellow',
    incident: {
      id: 'INC001235',
      title: 'Transaction VA01 timeout after transport',
      description: 'Sales order creation in transaction VA01 is timing out. Issue started yesterday after transport XYZ was applied. Multiple users in SD module affected. Response time exceeds 60 seconds.',
      error_code: 'TIMEOUT',
      component: 'SAP SD',
      severity: 'High',
      user_email: 'jane.smith@company.com',
      user_impact: '15 users in Sales department affected',
    },
    expectedConfidence: 65,
    expectedPath: 'assisted',
    diagnosticHints: [
      'Check database indexes on VBAK and VBAP tables',
      'Review transport XYZ contents for table changes',
      'Analyze table statistics in ST10',
      'Check for locked objects in SM12',
      'Review system load in ST06',
    ],
    timeSaved: '45 minutes',
    costSaved: '$45',
    slaMinutes: 60,
  },
  {
    id: 'escalate',
    name: 'Escalation Required',
    description: 'Critical system issue requiring expert team',
    icon: 'AlertOctagon',
    color: 'red',
    incident: {
      id: 'INC001236',
      title: 'ABAP memory dump affecting production',
      description: 'Multiple ABAP dumps with error TSV_TNEW_PAGE_ALLOC_FAILED occurring in production. Extended memory exhaustion suspected. Over 50 users affected. Business critical processes halted.',
      error_code: 'TSV_TNEW_PAGE_ALLOC_FAILED',
      component: 'SAP Basis',
      severity: 'Critical',
      user_email: 'operations@company.com',
      user_impact: '50+ users, business critical processes stopped',
    },
    expectedConfidence: 35,
    expectedPath: 'escalate',
    diagnosticHints: [
      'Check extended memory parameters (em/initial_size_MB)',
      'Review batch job scheduling for memory conflicts',
      'Analyze ST22 dumps for pattern recognition',
      'Check system logs in SM21',
      'Consider emergency memory parameter adjustment',
    ],
    timeSaved: '30 minutes',
    costSaved: '$30',
    slaMinutes: 15,
  },
]

export function getScenarioById(id: string): Scenario | undefined {
  return scenarios.find(s => s.id === id)
}
